site_name: Seminar Aktuelle Themen der künstlichen Intelligenz
nav:
- Aktuelles: index.md
- ...

theme: 
  name: material
  features:
    - navigation.expand
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
